server {
    listen 8080;
    location / {
      root   /usr/share/nginx/html;
      index  index.html index.htm;
      try_files $uri $uri/ /index.html;
    }
    add_header Content-Security-Policy "frame-ancestors self https://www.precision-medicine-portal.scilifelab.se/kiarva http://localhost:5173/kiarva;" always;
  }