// This is a customized shadcn component generated by V1 by Vercel. This component will not automatically update.

"use client";

import * as React from "react";
import Link from "next/link";
import { ChevronDown } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { ILink } from "@/interfaces/types";
import { usePathname } from "next/navigation";
import clsx from "clsx";
import { LINK_CLASSES } from "@/constants";

interface HeaderDropdownProps {
  links: { [id: string]: ILink };
}

export function HeaderDropdown({ links }: HeaderDropdownProps) {
  const pathname = usePathname();

  return (
    <DropdownMenu>
      <DropdownMenuTrigger className="text-lg hover:text-gray-300 transition-colors">
        Additional information <ChevronDown className="ml-1 h-4 w-4 inline" />
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        {Object.entries(links).map(([key, link]) => (
          <DropdownMenuItem key={key} asChild>
            <Link
              href={link.link}
              className={clsx(
                link.classes,
                LINK_CLASSES,
                "w-full",
                "hover:bg-primary hover:text-primary-foreground",
                pathname === link.link && "bg-primary text-primary-foreground"
              )}
            >
              {link.text}
            </Link>
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
